version: 1
formatters:
  # Two Formats - one simple and one for Threads containing the threadname
  simple:
    format: '%(asctime)s - %(processName)s - %(name)s - %(levelname)s - %(message)s'
  threadFormat:
    format: '%(asctime)s - %(name)s -%(relativeCreated)6d %(threadName)s - %(levelname)s - %(message)s'
  processFormat:
    format: '%(asctime)s - %(processName)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  # console
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  # logfile for the applocation: app_logfile.log
  rotatingFileHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: app_openrecall.log
    mode: 'a'
    maxBytes: 10485760 # 10MB
    backupCount: 0
    encoding: 'utf-8'
  rotatingThreadHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: threadFormat
    level: DEBUG
    filename: app_openrecall.log
    mode: 'a'
    maxBytes: 10485760 # 10MB
    backupCount: 0
    encoding: 'utf-8'
  rotatingProcessHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: processFormat
    level: DEBUG
    filename: app_openrecall.log
    mode: 'a'
    maxBytes: 10485760 # 10MB
    backupCount: 0
    encoding: 'utf-8'
  # combinedFileHandler: log everything into this file
  combinedFileHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: app_combined.log
    mode: 'a'
    maxBytes: 10485760 # 10MB
    backupCount: 0
    encoding: 'utf-8'
  # webFilehandler: log web server infos
  webFileHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: app_web.log
    mode: 'a'
    maxBytes: 10485760 # 10MB
    backupCount: 0
    encoding: 'utf-8'
  # only for logging of the logging configuration
  configFileHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: app_logging_config.log
    mode: 'a'
    maxBytes: 10485760 # 10MB
    backupCount: 0
    encoding: 'utf-8'
  # libraryHandler: log all information from the libraries
  libraryHandler:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    level: DEBUG
    filename: app_libraries.log
    mode: 'a'
    maxBytes: 10485760 # 10MB
    backupCount: 0
    encoding: 'utf-8'
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no
  root:
    level: STATUS
    handlers: [console,combinedFileHandler, rotatingProcessHandler]
    propagate: no
  app:
    level: DEBUG
    handlers: [rotatingProcessHandler,combinedFileHandler]
    propagate: no
  werkzeug:
    level: INFO
    handlers: [combinedFileHandler,webFileHandler]
    propagate: False
  logging_config:
    level: DEBUG
    handlers: [configFileHandler]
    propagate: False
  #logging of external modules
  default_library: &default_library_settings
    level: DEBUG
    handlers: [libraryHandler,combinedFileHandler]
    propagate: no
  torch:
    <<: *default_library_settings
  urllib3.connectionpool:
    <<: *default_library_settings
  PIL.Image:
    <<: *default_library_settings
  PIL.PngImagePlugin:
    <<: *default_library_settings
  h5py._conv:
    <<: *default_library_settings
  sentence_transformers.SentenceTransformer:
    <<: *default_library_settings
  torch.fx.passes.utils.matcher_utils:
    <<: *default_library_settings
  torch.fx.experimental.sym_node:
    <<: *default_library_settings
  torch.fx.experimental.symbolic_shapes:
    <<: *default_library_settings
  torch.onnx:
    <<: *default_library_settings
  torch.dynamo:
    <<: *default_library_settings
  transformers:
    <<: *default_library_settings
  huggingface_hub:
    <<: *default_library_settings
  requests:
    <<: *default_library_settings
  charset_normalizer:
    <<: *default_library_settings
  torch._functorch._aot_autograd:
    <<: *default_library_settings
  torch._inductor:
    <<: *default_library_settings
  torch._functorch.aot_autograd:
    <<: *default_library_settings
  torch._dynamo.backends.distributed:
    <<: *default_library_settings
  torch.distributed:
    <<: *default_library_settings
  c10d-NullHandler:
    <<: *default_library_settings
  torch._dynamo:
    <<: *default_library_settings
  tqdm:
    <<: *default_library_settings
